name: Haskell stack build

on:
  push:
    paths:
    - 'haskell/**'
    - 'stack*.yaml*'
    - '.github/*'
    - '.github/workflows/stack.yml'
  pull_request:
    paths:
    - 'haskell/**'
    - 'stack*.yaml*'
    - '.github/*'
    - '.github/workflows/stack.yml'

jobs:
  linux:
    runs-on: ubuntu-latest

    env:
      ARGS: "--stack-yaml stack.yaml --no-terminal --system-ghc --fast"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: 8.2.2
    - name: Install dependencies
      run: |
        stack build ${ARGS} --only-dependencies
    - name: Build
      run: |
        stack build ${ARGS}
