name: Haskell CI

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest

    env:
      ARGS: "--stack-yaml stack.yaml --no-terminal --system-ghc --fast"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.2'
    - name: Checkout submodules
      shell: bash
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Install dependencies
      run: |
        stack test ${ARGS} --only-dependencies
    - name: Build and test
      run: |
        stack test ${ARGS}
